apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: option-pricer-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    minSize: 2
    maxSize: 3
    #desiredCapacity: 2
    
  
cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["audit", "authenticator", "controllerManager"]
        # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
        # supported special values: "*" and "all"